---
- name: Перевод ноды в статус drain
  community.docker.docker_node:
    hostname: "{{ node_name }}"
    availability: drain

- name: Ожидание остановки ноды
  community.docker.docker_host_info:
    containers: true
  register: result
  retries: 10
  delay: 5
  until: result.host_info.ContainersRunning == 0
  delegate_to: "{{ node_name }}"

- name: Удаление ноды
  ansible.builtin.command: "docker node rm {{ node_name }} --force"
  # community.docker.docker_swarm:
  #   state: remove
  #   node_id: "{{ node_name }}"
  #   force: true
