---
- name: Deploy server / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    # - swarminit

- name: Manager
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarmjoin

- name: Worker
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarmjoin
