galaxy_info:
  role_name: deploy
  description: Выкладка микросервисов на docker cluster
  author: Mikhail Oznobikhin
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
